# SonarQube server settings
sonar.host.url=http://localhost:9000
sonar.token=squ_4e250f8a9451863d8848f5e5489d6e003e1f6218

# Project identification
sonar.projectKey=econ
sonar.projectName=econ
sonar.projectVersion=1.0

# Analysis settings
sonar.sources=client,config,controllers,helpers,middlewares,models,routes,server.js

# Coverage report path
sonar.javascript.lcov.reportPaths=coverage/frontend/lcov.info,coverage/backend/lcov.info

# Specify JavaScript as the main language
sonar.language=js

# Limit analysis to JavaScript files in the specified sources
sonar.inclusions=**/*.js

# Exclude test files from analysis
sonar.exclusions=**/*.test.js,**/*.integration.test.js,**/__mocks__/**,client/src/_site/**,coverage/**,playwright/**,playwright-report/**,test-results/**,e2e-tests/**,integration-tests/**,test-env-files/**